name: Post What Week Image

on:
  schedule:
    - cron: 0 17 * * 5 # Every Friday at 5:00 PM

  workflow_dispatch:

jobs:
  create_week_image_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: src

      - name: Download used images file
        uses: dawidd6/action-download-artifact@v3
        with:
          name: used_images
          path: ./src/
          if_no_artifact_found: warn
          search_artifacts: true

      - name: Run generate week image script
        run: python ./generate_week_image.py
        env:
          UNSPLASH_ACCESS_TOKEN: ${{ secrets.UNSPLASH_ACCESS_TOKEN }}
        working-directory: src

      - name: Upload used images log file
        uses: actions/upload-artifact@v4
        with:
          name: used_images
          path: ./src/used_images.txt

      - name: Upload week data
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/web

      - name: Deploy
        uses: actions/deploy-pages@v4

  post_to_instagram:
    runs-on: ubuntu-latest
    needs: create_week_image_and_deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: src

      - name: Run post to instagram script
        run: python post_ig.py
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        working-directory: src
