name: Post What Week Image

on:
  schedule:
    - cron: 0 17 * * 5 # Every Friday at 5:00 PM

  workflow_dispatch:

jobs:
  create_week_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Change Dir
        run: cd src

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download used images file
        uses: dawidd6/action-download-artifact@v3
        with:
          name: used_images
          path: ./
          if_no_artifact_found: warn
          search_artifacts: true

      - name: Run generate week image script
        run: python ./generate_week_image.py
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          UNSPLASH_ACCESS_TOKEN: ${{ secrets.UNSPLASH_ACCESS_TOKEN }}

      - name: Upload used images log file
        uses: actions/upload-artifact@v4
        with:
          name: used_images
          path: ./used_images.txt

      - name: Upload week data
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web

      - name: Deploy
        uses: actions/deploy-pages@v4

  post_to_instagram:
    runs-on: ubuntu-latest
    needs: create_week_image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Change Dir
        run: cd src

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run post to instagram script
        run: python ./post_to_instagram.py
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
