name: Post What Week Image

on:
    #schedule:
    # - cron: '0 0 * * 0' # Every Sunday at 00:00
    
    workflow_dispatch:

jobs:
    create_week_image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Script
              run: python main.py
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    